build: On linux when using libusb link with librt.
On lots of distributions libusb is linked with librt and when librt
is missing from the linker line there are errors like this:

  undefined reference to `clock_gettime'
  undefined reference to `clock_gettime'